name: ci

concurrency:
  group: "${{ github.ref_name }}"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0/5 * * * *" 
  
jobs:
  self-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with all the tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch the latest semantic version tag
        id: semver
        run: echo "latest-tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT
      - name: Bump me
        id: bump
        uses: licenseware/bump-version@main
        with:
          version: ${{ steps.semver.outputs.latest-tag }}
      - name: Configure git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      # - name: Fetch GPG Key
      #   run: |
      #     echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --import
      - name: Tag and push
        run: |
          git tag -a ${{ steps.bump.outputs.version }} -m "Bump version to ${{ steps.bump.outputs.version }}"
          git push origin ${{ steps.bump.outputs.version }}
      - name: Create a GitHub release from tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.bump.outputs.version }} --title "${{ steps.bump.outputs.version }}" --generate-notes --latest
