name: ci

concurrency:
  group: "${{ github.ref_name }}"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0/5 * * * *" 
  
jobs:
  self-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Bump me
        uses: licenseware/bump-version@main
        with:
          tag: "true"
          release: "true"
