name: ci

concurrency:
  group: "${{ github.ref_name }}"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 1 */1 * *"

jobs:
  self-test:
    if: ${{ github.event_name == "schedule" }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Bump me
        uses: licenseware/bump-version@main
        with:
          release: "true"
          tag: "true"
          token: ${{ secrets.GITHUB_TOKEN }}

  checks:
    if: ${{ github.event_name == "push" }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -U pip pre-commit
      - name: Run pre-commit
        run: pre-commit run -a
